### PR TITLE
Fix: Indent after oneCommandCode on comment, block comment, empty line. Formatting inside block comment.

### LINKED ISSUE #59: Format document: After "if" statement without brackets a comment is formatted wrong
### Description

After "if" statement without brackets a comment is formatted wrong.

### Unformatted input snippet

```autohotkey
if (true)
; comment
   success = 1
else
   success = 1
```

### Expected formatted output snippet

```autohotkey
if (true)
   ; comment
   success = 1
else
   success = 1
```

### Actual formatted output snippet

```autohotkey
if (true)
   ; comment
success = 1
else
   success = 1
```

Thanks in advance

### LINKED ISSUE #185: Wrong indentation inside block comment
### Description

Wrong indentation inside block comment

### Unformatted input snippet

```autohotkey
foo () {
/*
typedef struct TEST {
DWORD cbSize;          0
} CMINVOKECOMMANDINFOEX;
*/
/*
MsgBox, This line is commented out (disabled).
MsgBox, Common mistake: */ this does not end the comment.
MsgBox, This line is commented out. 
*/
/*
bar() {
Loop, 4 {
MsgBox % A_Index
}
if (true) {
SoundBeep
} else {
MsgBox
}
}
if (true)
ToolTip
*/
MsgBox
}
```

### Expected formatted output snippet

```autohotkey
foo () {
    /*
    typedef struct TEST {
        DWORD cbSize;          0
    } CMINVOKECOMMANDINFOEX;
    */
    /*
    MsgBox, This line is commented out (disabled).
    MsgBox, Common mistake: */ this does not end the comment.
    MsgBox, This line is commented out. 
    */
    /*
    bar() {
        Loop, 4 {
            MsgBox % A_Index
        }
        if (true) {
            SoundBeep
        } else {
            MsgBox
        }
    }
    if (true)
        ToolTip
    */
    MsgBox
}
```

### Actual formatted output snippet

```autohotkey
foo () {
/*
typedef struct TEST {
DWORD cbSize;          0
} CMINVOKECOMMANDINFOEX;
    */
/*
MsgBox, This line is commented out (disabled).
    MsgBox, Common mistake: */ this does not end the comment.
    MsgBox, This line is commented out. 
    */
/*
bar() {
Loop, 4 {
MsgBox % A_Index
}
if (true) {
SoundBeep
} else {
MsgBox
}
}
if (true)
ToolTip
    */
    MsgBox
}
```

### PR DESCRIPTION
**Pull request by kyklish**
Closes #59.
Closes #185.

Changes proposed in this pull request:

-   more universal search of begin `/*` and end `*/` block comment pattern
-   extract save indented line code to `buildIndentedLine(...)` function
-   don't reset `oneCommandCode` if current line is empty, single line comment or block comment
-   save indent values on block comment enter and restore them on block comment exit
-   add directives for formatter `;@AHK++FormatBlockCommentOn` and `;@AHK++FormatBlockCommentOff` to format code inside block comments
-   add directives to snippets

In:
```autohotkey
foo () {
;@AHK++FormatBlockCommentOn
/*
typedef struct TEST {
DWORD cbSize;          0
} CMINVOKECOMMANDINFOEX;
*/
/*
MsgBox, This line is commented out (disabled).
MsgBox, Common mistake: */ this does not end the comment.
MsgBox, This line is commented out. 
*/
/*
bar() {
Loop, 4 {
MsgBox % A_Index
}
if (true) {
SoundBeep
} else {
MsgBox
}
}
if (true)
ToolTip
MsgBox
*/
;@AHK++FormatBlockCommentOff
MsgBox
/*
    All text in this block comment must save original indent
bar() {
        Loop, 4 {
                MsgBox % A_Index
        }
}
*/
}
```
Out:

```autohotkey
foo () {
    ;@AHK++FormatBlockCommentOn
    /*
    typedef struct TEST {
        DWORD cbSize;          0
    } CMINVOKECOMMANDINFOEX;
    */
    /*
    MsgBox, This line is commented out (disabled).
    MsgBox, Common mistake: */ this does not end the comment.
    MsgBox, This line is commented out. 
    */
    /*
    bar() {
        Loop, 4 {
            MsgBox % A_Index
        }
        if (true) {
            SoundBeep
        } else {
            MsgBox
        }
    }
    if (true)
        ToolTip
    MsgBox
    */
    ;@AHK++FormatBlockCommentOff
    MsgBox
    /*
        All text in this block comment must save original indent
    bar() {
            Loop, 4 {
                    MsgBox % A_Index
            }
    }
    */
}
```
Notifying @mark-wiemer

### CODE REVIEW

File: src/providers/formattingProvider.ts [hunk 1]
```diff
@@ -66,8 +71,9 @@ export class FormatProvider implements vscode.DocumentFormattingEditProvider {
             const formattedLine = originalLine
                 .replace(/^\s*/, '')
                 .replace(/;.+/, '')
-                .replace(/ {2,}/g, ' ')
+                .replace(/\s{2,}/g, ' ')
```
Comment (mark-wiemer) [inline src/providers/formattingProvider.ts:74]: If the user indents with tabs, won't this replace tabs with spaces? I think we should leave this behavior as-is please :) we can address it in a separate PR if necessary.

**Review by mark-wiemer — CHANGES_REQUESTED** [review]
Thanks so much, this is great code! It'd be awesome if we could update the tests in this PR as well, please let me know if you have any questions.

File: src/common/codeUtil.ts [hunk 2]
```diff
@@ -8,12 +8,13 @@ export class CodeUtil {
...
         }
         return original
-            .replace(/;.+/, '')
             .replace(/".*?"/g, '""') // replace string literals with empty string literal
             .replace(/{.*}/g, '') // remove matching braces
             .replace(/ +/g, ' ')
             .replace(/\bgui\b.*/gi, '')
-            .replace(/\b(msgbox)\b.+?%/gi, '$1');
+            .replace(/\b(msgbox)\b.+?%/gi, '$1')
+            .replace(/;.+/, '') // remove comments must be last, semicolon may be inside string (expression) or 'MsgBox, { ; comment with close brace }'
```
Comment (mark-wiemer) [inline src/common/codeUtil.ts:16]: Can we add some unit tests for `purify`? We can add them in `extension.test.ts` for now.

File: src/providers/formattingProvider.ts [hunk 3]
```diff
@@ -57,6 +57,11 @@ export class FormatProvider implements vscode.DocumentFormattingEditProvider {
         let oneCommandCode = false;
         let blockComment = false;
         let atTopLevel = true;
+        /** Save important values to this variables on block comment enter, restore them on exit */
+        let blockCommentDepth = 0;
```
Comment (mark-wiemer) [inline src/providers/formattingProvider.ts:61]: Let's add a formatting sample file with an indented block of code here

**Review by mark-wiemer — CHANGES_REQUESTED** [review]

File: src/providers/formattingProvider.ts (hunk 1 above)
Comment (kyklish) [reply src/providers/formattingProvider.ts]: Done

File: src/common/codeUtil.ts (hunk 2 above)
Comment (kyklish) [reply src/common/codeUtil.ts]: I revert this changes, this function modified in #159

File: src/providers/formattingProvider.ts (hunk 3 above)
Comment (kyklish) [reply src/providers/formattingProvider.ts:61]: Done.

**Comment by kyklish** [comment]
Who must press `Resolve conversation` on requested changes, when I add requested changes?

**Comment by kyklish** [comment]
Will extract block comment formatting to separate PR (add meta command for formatter `@FormatBlockComment` [add it to snippets])

File: src/providers/formattingProvider.ts [hunk 4]
```diff
@@ -77,19 +94,71 @@ export class FormatProvider implements vscode.DocumentFormattingEditProvider {
...
             }
-            if (originalLine.match(/ *\*\//)) {
-                blockComment = false;
-            }
+
             if (blockComment) {
-                formattedDocument += originalLine;
-                if (lineIndex !== document.lineCount - 1) {
-                    formattedDocument += '\n';
+                // Save block comment line only if user don't want format it content
```
Comment (mark-wiemer) [inline src/providers/formattingProvider.ts:130]: Can you expand on what this means? I don't follow "only if user don't want format it content" :/

File: src/providers/formattingProvider.ts [hunk 5]
```diff
@@ -77,19 +94,71 @@ export class FormatProvider implements vscode.DocumentFormattingEditProvider {
...
+                if (!formatBlockComment) {
+                    let blockCommentLine = '';
+                    if (originalLine.indexOf(blockCommentIndent) === 0) {
```
Comment (mark-wiemer) [inline src/providers/formattingProvider.ts:133]: Minor perf improvement

```suggestion
                    if (originalLine.startsWith(blockCommentIndent)) {
```

File: src/providers/formattingProvider.utils.ts [hunk 6]
```diff
@@ -1,3 +1,57 @@
+import * as vscode from 'vscode';
+
+/**
+ * Build indentation chars
+ * @param depth Depth of indent
+ * @param options VS Code formatting options
+ */
+export function buildIndentationChars(
+    depth: number,
+    options: vscode.FormattingOptions,
```
Comment (mark-wiemer) [inline src/providers/formattingProvider.utils.ts:10]: This way, when we are creating mock data, we only have to mock the `tabSize` property instead of all the properties

```suggestion
    options: Pick<vscode.FormattingOptions, 'tabSize'>
```

File: src/test/suite/format/samples/ahk-explorer.out.ahk [hunk 7]
```diff
@@ -3493,25 +3493,25 @@ return
...
 
 $esc::
-    if (focused="flistView") {
-        if (canRename) {
-            canRename:=false
-            ; gui, renameSimple:Default
-            ; gui, submit
-            gui, main:Default
-            ControlFocus,, % "ahk_id " ListviewHwnd%whichSide%
+if (focused="flistView") {
```
Comment (mark-wiemer) [inline src/test/suite/format/samples/ahk-explorer.out.ahk:3496]: Do we know why we are no longer indenting after labels? Is this intentional? I understand that all code under a label is executed until a `return` statement is hit, but generally each label has its own return statement.

I'm not sure users would appreciate this change, but I may be wrong. Do you have code samples that show code is usually not indented after a label?

My personal preference would be to make all labels have no indent, but code under them (up to and including return statements) has one level of indentation.

```
$esc::
    doThing()
^a::
    doAnotherThing()
    return

functionCallOutsideLabel()

#x::
    lastThing()
    return
moreCodeHere()
```

File: src/test/suite/format/samples/ahk-explorer.out.ahk [hunk 8]
```diff
@@ -3493,25 +3493,25 @@ return
...
-    send, {enter}
+    return
+}
+send, {enter}
 return
 
 #if winactive("create_folder ahk_class AutoHotkeyGUI")
 
-$enter::
+    $enter::
```
Comment (mark-wiemer) [inline src/test/suite/format/samples/ahk-explorer.out.ahk:3514]: This label is indented because it comes after an `#if` directive, right? I thought we discussed that this is not intended behavior, as `#if` directives apply for all code below them. If this `$enter::` label is indented, shouldn't `$+enter::` and `$^+enter::` (lines 3519 and 3520) also be indented?

**Review by mark-wiemer — CHANGES_REQUESTED** [review]

File: src/providers/formattingProvider.ts (hunk 4 above)
Comment (kyklish) [reply src/providers/formattingProvider.ts:130]: By default, the user does not want format text inside a block comment. The formatter stores the line directly in the result variable `formattedDocument` and immediately moves to the next line of the document.

If the user sets the directive `;@AHK++FormatBlockCommentOn`, he wants to format the text within the block comment. The variable `formatBlockComment` becomes `true` and the formatter does not save the line, but parses it like regular code.

File: src/test/suite/format/samples/ahk-explorer.out.ahk (hunk 8 above)
Comment (kyklish) [reply src/test/suite/format/samples/ahk-explorer.out.ahk:3514]: Formatter detects `#if` directive like `if` command. #159 fix this. When I merge `main` branch it must gone away.

File: src/providers/formattingProvider.utils.ts (hunk 6 above)
Comment (kyklish) [reply src/providers/formattingProvider.utils.ts:10]: But this function needs two property: `tabSize` and `insertSpaces`. 

Change this:

`buildIndentedLine(..., options) -> buildIndentationChars(..., options)`

to this:

`buildIndentedLine(..., tabSize, insertSpaces) -> buildIndentationChars(..., tabSize, insertSpaces)` ?

File: src/test/suite/format/samples/ahk-explorer.out.ahk (hunk 8 above)
Comment (kyklish) [reply src/test/suite/format/samples/ahk-explorer.out.ahk:3514]: Now `#if` directive detects like `if` command and formatter apply rules for `one command code` scenario. When this PR and
#181 will be merged to `main` branch this wrong behavior eliminates.

File: src/test/suite/format/samples/ahk-explorer.out.ahk (hunk 7 above)
Comment (kyklish) [reply src/test/suite/format/samples/ahk-explorer.out.ahk:3496]: > Do we know why we are no longer indenting after labels?
No.
> Is this intentional?
No.

File: src/providers/formattingProvider.ts (hunk 4 above)
Comment (kyklish) [reply src/providers/formattingProvider.ts:131]: Please, suggest proper comment.

File: src/providers/formattingProvider.utils.ts (hunk 6 above)
Comment (mark-wiemer) [reply src/providers/formattingProvider.utils.ts:10]: Not sure how I missed `insertSpaces`, anyway, `Pick` can support any number of properties, so let's just do this:

```suggestion
    options: Pick<vscode.FormattingOptions, 'insertSpaces' | 'tabSize'>,
```

File: src/test/suite/format/samples/ahk-explorer.out.ahk (hunk 8 above)
Comment (mark-wiemer) [reply src/test/suite/format/samples/ahk-explorer.out.ahk:3514]: Alright, we've now merged #181, let's update this PR to reflect those changes.

**Review by mark-wiemer — CHANGES_REQUESTED** [review]

**Comment by kyklish** [comment]
Done.

**Review by mark-wiemer — APPROVED** [review]
