### PR TITLE
Compiler GUI

### LINKED ISSUE #243: Add option to invoke the compiler GUI from the context menu
Would it be possible to add an option to invoke the compiler GUI from the context menu?

### LINKED ISSUE #253: Compile never saved file
## Description

Extension try compile never saved file.

## Reproduction steps

1. Create new file.
2. Try compile.
3. See error

Error

## Expected behavior

VS Code error message.

Expected

## Additional context

Original extension has solution, but it is broken.

### PR DESCRIPTION
**Pull request by kyklish**
Closes #243.
Closes #253.

Changes proposed in this pull request:

- new command `ahk++.compilerGui`
- new context menu `Compiler GUI`

Notifying @mark-wiemer

### CODE REVIEW

**Comment by kyklish** [comment]
New checks?

File: src/service/runnerService.ts [hunk 1]
```diff
@@ -62,11 +62,12 @@ export class RunnerService {
         const pos = currentPath.lastIndexOf('.');
         const compilePath =
             currentPath.substr(0, pos < 0 ? currentPath.length : pos) + '.exe';
+        const guiKey = showGui ? '/gui' : '';
         if (
             await Process.exec(
                 `"${Global.getConfig(
```
Comment (mark-wiemer) [inline src/service/runnerService.ts:68]: Let's see if we can create a pure helper function that generates this string that's passed to `Process.exec`. We can use the internal-external pattern from the formatter. Then we can just test the pure helper function and call it tested :)

**Review by mark-wiemer — CHANGES_REQUESTED** [review]

File: package.json [hunk 2]
```diff
@@ -61,6 +61,11 @@
                 "category": "AHK++",
                 "icon": "./image/build.svg"
             },
+            {
+                "command": "ahk++.compilerGui",
+                "title": "Compiler GUI",
```
Comment (mark-wiemer) [inline package.json:66]: Let's keep this as close to the default File Explorer context menu command name as we can for familiarity. We just have to specify "AHK" script since we're in an environment that supports many languages

```suggestion
                "title": "Compile AHK Script (GUI)",
```

**Review by mark-wiemer — CHANGES_REQUESTED** [review]
thanks again :)

File: src/service/runnerService.ts (hunk 1 above)
Comment (kyklish) [reply src/service/runnerService.ts]: Done

**Review by mark-wiemer — APPROVED** [review]

**Comment by fade2gray** [comment]
@kyklish @mark-wiemer  Thank you.
